services:
  bot:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
      - BOT_PORT=8080
      - DEFAULT_SECRET_TOKEN=${DEFAULT_SECRET_TOKEN}
      - HMAC_DEFAULT_SECRET=${HMAC_DEFAULT_SECRET}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - AUTH0_API_URL=${AUTH0_API_URL}
      - BASE_URL=${BASE_URL}
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped